### ISSUE TITLE
Critical bug: KeyError

### ISSUE THREAD

**Issue by KiK0S** [abarankab/labyrinth_generator#1]
When dimensions aren't equal, produces KeyError while trying to remove some walls.
input `10 20`
in my case leads to

`File "tmp.py", line 19
    self.generate([random.randint(0, h - 1), random.randint(0, w - 1)])`
`File "tmp.py", line 67
    self.walls.remove(self.get_wall(pos, move))`
`KeyError: (6, 15, 6, 16)`

**Comment by abarankab** [comment]
Fixed in https://github.com/abarankab/labyrinth_generator/commit/6967646955a191ea83b3af8365d67dc61a8c0ccb
